### PR TITLE
Move Admin to Denkmal namespace: Login, Logout, AuthRequired; forms, actions, page, layouts

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam could you have a look;

- moved admin login/logout/auth stuff to denkmal
- added denkmal_page_login
- updated `headerbar` with login/logout (must be styled)

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
remove login cmp

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
lgtm!
Merge and do "change password" in a followup?

**Pull request merged**
