### PR TITLE
Filter chat by venue

### PR DESCRIPTION
**Pull request by njam**

### CODE REVIEW

**Comment by njam** [comment]
@christopheschwyzer @NicolasSchmutz @kris-lab
Not sure about the "filter" approach. Alternatively we could show a header, and omit the venue in each message.
wdyt?

screen shot 2015-02-25 at 20 34 38

**Comment by christopheschwyzer** [comment]
Agree on omitting the when Filter is active. Maybe Filter part could be right-aligned, ...  or centered. not sure.

**Comment by njam** [comment]
Maybe more like a big heading at the top with the venue name, then below the venue-less msg list?

**Comment by kris-lab** [comment]
Agree:
- filter should be centered
- Venue name for each message should be remove. Timestamp should stay.

**Comment by njam** [comment]
How do you like this?:
screen shot 2015-02-28 at 15 33 09

**Comment by njam** [comment]
Pair-reviewed with @christopheschwyzer

**Comment by NicolasSchmutz** [comment]
:heart: love it!

**Pull request merged**
