### PR TITLE
adopt CM_Image_Image changes

### PR DESCRIPTION
**Pull request by alexispeter**
depends on https://github.com/cargomedia/CM/pull/1667

### CODE REVIEW

**Comment by njam** [comment]
Thanks!
Shouldn't `Denkmal_Model_MessageImage::create()` receive an Image instead of a File?

**Comment by alexispeter** [comment]
Was a bit conflicted about this. Requiring a file instead of an image helps avoid memory-problems we had in the past with processes handling tons of pictures.
In the end it doesn't really matter since we pretty much always use a tmp-file in our upload-processes.

**Comment by njam** [comment]
But here in the API you send the image's blob. Now we create a temp file of the blob, to then again read that file. We're using an S3 filesystem here too, so that adds quite some delay!

Sooner or later you always need to load the data into memory, I don't think it makes a difference here?

**Comment by alexispeter** [comment]
Then let's change it.

**Comment by alexispeter** [comment]
How about introducing an `in-memory` file? Or some abstract container-object? Overkill? :>

**Comment by njam** [comment]
Well but here we mostly want to pass along image data and not a file, so I don't see the advantage of using an abstract "memory container", it would just be a "string" of bytes. Would there be an advantage?

**Comment by alexispeter** [comment]
No

**Comment by alexispeter** [comment]
please review @njam

**Comment by njam** [comment]
lvgtm

**Comment by njam** [comment]
Closing in favor of https://github.com/denkmal/denkmal.org/pull/484

**Pull request closed without merging**
