### PR TITLE
add translations dependent on browser language

### PR DESCRIPTION
**Pull request by christopheschwyzer**
- Translate to english
- Add Translations page to Admin
- Add TranslationList cmp

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
@njam I guess we need to write an update script to delete all language keys?

**Comment by christopheschwyzer** [comment]
@njam please review

**Comment by njam** [comment]
- Denkmal_Menu_Main

Didn't test it, but trust you did.

**Comment by christopheschwyzer** [comment]
...The weekdays are the only translations missing. Not sure how this works. They will probably have 3?! letters in English? :/

**Comment by njam** [comment]
It's using the first 2 letters of a translation - see `smarty_function_date_weekday`.

**Comment by njam** [comment]
lgtm

**Pull request merged**
