### PR TITLE
Hipsters tags paging

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
- Denkmal_Paging_Tag_Venue_Hipster: Move modelType where into JOIN?
- Denkmal_Paging_Tag_Venue_Hipster: Allow to pass $createdMin
- Tests: something like `(new DateTime())->sub(new DateInterval('P1H'));`

**Comment by kris-lab** [comment]
@njam please have a look

**Comment by njam** [comment]
- Denkmal_Paging_Tag_Venue_Hipster: I would use DateTime or unix timestamp for $createdMin. Now with string it can be used for sql injection.

Rest looks good

**Comment by kris-lab** [comment]
@njam have a look

**Comment by njam** [comment]
lgtm

**Pull request merged**
