### PR TITLE
Redesign concept

### PR DESCRIPTION
**Pull request by christopheschwyzer**
- Add click feedback

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
Proposition:
- We discussed this before - however - how about unifying the experience with one logo for all regions ->I thought an owl would fit: Active at night, observing, smart. (downside: tripadviser has similar)
- Introduce a "dark" theme that will be active during the night from _sunset_ to _sunrise_.
- Drop the ".org" ending from the logo

screen shot 2016-09-18 at 21 08 30
screen shot 2016-09-18 at 21 08 57

@denkmal/core thoughts?

**Comment by christopheschwyzer** [comment]
I also did some experiments with other logos - don't think they work so well.
screen shot 2016-09-18 at 21 20 06
screen shot 2016-09-18 at 21 20 14
screen shot 2016-09-18 at 21 20 23

maybe you have other ideas - we can of course use baslerstab/graz tower.

**Comment by njam** [comment]
Cool!

What I like:
- I like the idea of using 1 logo.
- Owl is nice. Disco ball would be great!
- Header-bar looks and works much better.
- Great idea with the night theme!

What I would change:
- The contrast of the event list should be increased I think. Description and venue names have quite weak contrast, although they're the main content of the site.
- I'm not too fond of the logo font, but that might be just me

**Comment by NicolasSchmutz** [comment]
super cool, thanks a lot!

I like:
- the new green
- owl
- the idea of one logo
- dark theme

I would change/keep:
- I would stick to the old font - gut feeling
- I would keep the ".org" as it's IMO part of the brand and much easier to find on google
- not sure about the green venue names
- although I like it I'm not sure about the owl. It's a very nice idea but also very similar to tripadvisor :(

>The contrast of the event list should be increased I think. Description and venue names have quite weak contrast, although they're the main content of the site.

agree with Reto

**Comment by NicolasSchmutz** [comment]
@trampy we're all very in favor of using only 1 logo. The owl would be really great:
>Active at night, observing, smart.

wdyt?

**Pull request merged**
