### PR TITLE
Add scraper for Apawi

### PR DESCRIPTION
**Pull request by njam**

### CODE REVIEW

**Comment by NicolasSchmutz** [comment]
@njam scraper works but the artist is missing. I only get title and genre. Could you double check?

**Comment by njam** [comment]
Here's an example entry:
```
 <item> <title>Wednesday Live: Yatatchi</title>
 <link>http://apawi.ch/event/wednesday-live-yatatchi</link>
 <description>&lt;p&gt;&lt;b&gt;Mittwoch, 27. April 2016 - 18:00 bis 1:00&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;«guter Afro Jazz»: &lt;br /&gt;Lounge ab 18:00, Live Band ab 20:30 bis 01:00
 mit Jazz, Blues, Latin and African Jazz&lt;/p&gt;
&lt;p&gt;&lt;img src=&quot;http://apawi.ch/sites/default/files/styles/wasserzeichen_klein/public/events/cover/Apawi_Live_20160220_Yatatchi_cover.jpg?itok=Qu9yGYdy&quot; width=&quot;393&quot; height=&quot;184&quot; alt=&quot;&quot; /&gt;&lt;/p&gt;
&lt;p&gt;Yatatchi, der mit bürgerlichem Namen Patrick Renaud Tatih heisst, stammt aus Pointe-Noire, der Wirtschaftshauptstadt der Republik Kongo. Daher stammt auch sein Beiname MUAN NDJINDJI, was in der lokalen Sprache Vili Sohn Pointe-Noires bedeutet. Als professioneller Musiker hat Yatatchi viele Preise und Auszeichnungen erhalten, im Kongo, in Frankreich und in den USA. Von Zeit zu Zeit spielt er mit anderen internationalen Künstlern wie etwa Manu Dibango, Orlando Julius oder Majid Bekkas , was einen faszinierenden Fusion Sound ergibt. Yatatchi ist der Organisator eines jährlichen internationalen Musikfestivals, La Fête à Ndjindji, in seiner Heimatstadt Pointe-Noire.

Inzwischen ist Basel, die Schweizer Kulturhauptstadt, zu seiner zweiten Heimat geworden. Hier feierte er im Stadt-Casino sein 15-jähriges Bühnenjubiläum und hier spielte er auch sein drittes Album, TCHILUMBU TCHI KELI (Der Tag wird kommen), ein. In Basel treffen die verschiedensten musikalischen Kulturen und Traditionen aufeinander – in seinem neuesten Werk widmet Yatatchi der Stadt, die ihn aufgenommen hat, ein spezielles Lied. Darüber hinaus organisiert er jedes Jahr das Musikfestival AFROSU Event, sein Beitrag zur musikalischen Zusammenarbeit von Schweiz und Afrika.

Yatatchi (Trompete, Gesang), Peter Gysin (Gitarre, Gesang), Willy Surbeck (Bass), Louie Maiello (Schlagzeug)
&lt;/p&gt;</description>
 <author>Apawi Events</author>
 <category>Jazz, Blues, Latin and African Jazz</category>
 <guid isPermaLink="false">194</guid>
 <pubDate>Fri, 22 Apr 2016 17:51:01 +0200</pubDate>
 <source url="http://apawi.ch/events/feed">Event Programm</source>
 <ev:location>Apawi Pure Lounge, Rheingasse 8, Basel</ev:location>
 <ev:organizer>by Apawi or 3rd party promoters</ev:organizer>
 <ev:type>Jazz, Blues, Latin and African Jazz</ev:type>
 <ev:startdate>Wed, 27 Apr 2016 18:00:00 +0200</ev:startdate>
 <ev:enddate>Thu, 28 Apr 2016 01:00:00 +0200</ev:enddate>
</item>
```

We're using "title" and "category".
There's also "description", but it's quite long usually, so I didn't use it.
Afaics usually the "title" includes the artist(s) though.
wdyt?

**Comment by NicolasSchmutz** [comment]
Unfortunately many events have the artist only in the description. Not sure how to solve this, the long description is also problematic...

One example:
````
 <item> <title>«Thanks God, it`s Afterwork!»</title>
 <link>http://apawi.ch/event/thanks-god-its-afterwork</link>
 <description>&lt;p&gt;&lt;b&gt;Donnerstag, 28. April 2016 - 18:00 bis 2:00&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;«Chill zu House, Pop, Funk &amp; RnB mit DJ Raykard»: &lt;br /&gt;Lounge ab 18:00h, DJ ab Party 19:00 bis 02:00
 mit Chill zu House, Pop, Funk &amp; RnB&lt;/p&gt;
````

**Comment by njam** [comment]
How about asking them to always include the most relevant information in the "title"?

**Comment by NicolasSchmutz** [comment]
done

**Pull request merged**
