### PR TITLE
Event Details "more" design

### PR DESCRIPTION
**Pull request by njam**
TODO:
- No margin if empty
- Event date+time

### CODE REVIEW

**Comment by njam** [comment]
Nicolas and I tried to clean up the event details' "more" section, especially when there's a lot of content.

Before:
image

After:
image

wdyt?

The date+time of the event looks like it's a bit in the wron place, but we couldn't fix it. Should it be on the same height as the venue name? And maybe a single line?

**Comment by christopheschwyzer** [comment]
screen shot 2017-03-12 at 17 11 32

works for me. I adjusted spacing a bit. Hope it's ok.

**Comment by christopheschwyzer** [comment]
We could move the date/time and move it under the event description in line with the links. I haven't tried it. Might be ok as is for first version.

**Comment by christopheschwyzer** [comment]
This kind of music playing animation would be nice as well:
6rgfsghpm4

**Comment by njam** [comment]
thanks

**Pull request merged**
