### PR TITLE
Add region to venue model 

### PR DESCRIPTION
**Pull request by fvovan**
- To Venue
- To Denkmal_Scraper_Source_Abstract

### CODE REVIEW

**Comment by njam** [comment]
Pass venue from /add page down to EventAdd form: https://github.com/denkmal/denkmal.org/compare/master...njam:add-form-region

**Comment by fvovan** [comment]
It took some time to realise that for `_process(CM_Params $params, CM_Http_Response_View_Form $response, CM_Form_Abstract $form)` `$params` and `$form->params` are different values.
@njam please review

**Comment by njam** [comment]
Could you merge upstream or rebase?

**Comment by njam** [comment]
And maybe merge in https://github.com/denkmal/denkmal.org/pull/539 ?

**Comment by njam** [comment]
- Denkmal/Model/Region.php: getByAbbreviation: I would suggest that we identify regions by the "slug", because it should never change (as it's part of the URL). So how about instead introducing a `getBySlug` (which fails if `findBySlug()` doesn't find one)?
 - This could also be used in `Denkmal_Site_Region_Abstract::getRegion`
- Denkmal/Model/Venue.php: Usually the convention is to call it just `region` (instead of `regionId`), if it's using the automatism of the model schema.
- Model/Venue.php: toArrayApi: I would leave this untouched for now. Having just an "id" might not be so useful on the API. Not sure what is best. But I put a bullet point "API" into https://github.com/denkmal/denkmal.org/issues/506 - so  I think we can revisit it later

**Comment by fvovan** [comment]
@njam  please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
