### PR TITLE
Account page; Change password

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please have a look

**Comment by njam** [comment]
- ChangePassword/Process.php: Check german
- Denkmal_Component_Account: Remove?
- Denkmal_FormAction_ChangePassword_Process: popinComponent not needed
- Remove DenkmalTest_TestCase and DenkmalTest_TH?

**Comment by kris-lab** [comment]
@njam please have a look

**Comment by njam** [comment]
looks good!

**Pull request merged**
