### PR TITLE
Custom google maps theme

### PR DESCRIPTION
**Pull request by christopheschwyzer**
closes https://github.com/denkmal/denkmal.org/issues/688

Current theme: https://snazzymaps.com/style/229/simple-and-light (`google-maps-styles.json`)

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
A few experiments: (current one used is bottom row, first from left)
map-themes

@njam @NicolasSchmutz let me know

**Comment by christopheschwyzer** [comment]
current solution: (usually there is less content of course)
details

@njam please have a closer look at the _php_ part. Not the files are in the right place, etc.

**Comment by NicolasSchmutz** [comment]
cool! current solution sgtm

**Comment by njam** [comment]
I also liked the 2nd version. With the dark/blue colors it reminds of night(life).

- Denkmal_GoogleMaps_JsonToStaticParams: when using a separate class for a helper function you can make the function non-static. That has the nice advantage that you could store some state on the class if needed. The usage will then be like: `$mapsParams = new MapsParams(); $styles = $mapsParams->getStyles($jsonStyles);`.
  - Probably it would be also a good idea to move the *whole* Google Maps Image Renderer into a class (including the styles logic), which would make it more testable. The smarty function would then just instantiate the helper and call a function on it.
- Denkmal_GoogleMaps_JsonToStaticParams: Instead of `json_encode()` please use `CM_Util::jsonEncode()` which has additional error checking.
- function.googlemaps_img.php: Instead of using `CM_Params::encode()` please use `CM_Util::jsonEncode()` if you only need to encode json. 
- function.googlemaps_img.php: It looks strange that the URL parameter `style=` is left unencoded, and later we json-encode it before appending it to the URL. I assume it should be URL-encoded. The best would be to add it to the existing `$linkParams` which is automatically URL-encoded in `CM_Util::link()`.
  - One problem will be that we want to have *multiple* `style=` URL parameters. But iirc it was also possible to append multiple styles with a different separator. Was it "|"?

**Comment by christopheschwyzer** [comment]
I'm not sure I understood everything :)
> One problem will be that we want to have multiple style= URL parameters. But iirc it was also possible to append multiple styles with a different separator. Was it "|"?

I didn't see any other option than doing it manually 
```php
 $stylesParams .= '&style=' . urlencode($style);
```

We could do something like: `$linkParams['style'] = [$styles] `- but then we'd have to _preg_replace_ some parts out of the final link again. Maybe I'm missing something. 

> function.googlemaps_img.php: Instead of using CM_Params::encode() please use CM_Util::jsonEncode() if you only need to encode json.

I didn't get that 😭 - I understood `CM_Params::encode() ` doesn't encode a string? I used `urlencode` instead.

**Comment by njam** [comment]
Should we pair on it? Do you maybe have a few hours on the weekend? We could finish a few other things together as well.

**Comment by christopheschwyzer** [comment]
Friday afternoon or earlier on Saturday sgtm!

**Pull request merged**
