### PR TITLE
Adjust Denkmalmit banner

### PR DESCRIPTION
**Pull request by christopheschwyzer**

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
@njam Do we have to adjust something regarding already dismissed banners? Or is "clearing" local storage during the deployment?

**Comment by njam** [comment]
Local storage will persist. I think best would be to change the local storage key.

**Comment by christopheschwyzer** [comment]
🔝

**Comment by njam** [comment]
it's live

**Comment by christopheschwyzer** [comment]
🔝

**Comment by NicolasSchmutz** [comment]
@njam if you have a spare minute, could you remove the banner from denkmal.org/graz. I doubt that we can continue the project in Graz...

**Pull request merged**
