### PR TITLE
Link venue in messageList to filtered chat

### PR DESCRIPTION
**Pull request by njam**
Part of #417

### CODE REVIEW

**Comment by njam** [comment]
@christopheschwyzer fyi

**Comment by njam** [comment]
@christopheschwyzer please double check

**Comment by christopheschwyzer** [comment]
I like it. Not sure about the blue color :)

**Comment by njam** [comment]
> Not sure about the blue color :)

It's black now - did you want it blue?

**Comment by christopheschwyzer** [comment]
No, black is fine! thanks

**Pull request merged**
