### PR TITLE
Design Regions page

### PR DESCRIPTION
**Pull request by christopheschwyzer**

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
@njam please review

**Comment by christopheschwyzer** [comment]
…design not final yet

**Comment by njam** [comment]
Looks good so far.

site-specific resources can be included with: https://github.com/cargomedia/cm/pull/2170

**Comment by njam** [comment]
Also we should add good copy (and markup) for google.

**Comment by christopheschwyzer** [comment]
Suits the purpose - but I'm not happy yet. Not sure about the text. Ideas?
screen shot 2016-05-23 at 13 36 37

@NicolasSchmutz @njam ideas?

**Comment by trampy** [comment]
I like the idea to use photos instead of logos. „Graz AT“ is maybe a bit difficult to read in this version. What do you think?
Regarding text: Definitely fits the purpose!

**Comment by christopheschwyzer** [comment]
@trampy agree. Maybe you have a suitable photo? (I used one from wikipedia)

**Comment by NicolasSchmutz** [comment]
Maybe something like: " What's up in your city?" instead of the welcome title? 
Maybe grey out the pictures a bit?

**Comment by njam** [comment]
Nice! Great text!
How about no title at all?

**Comment by njam** [comment]
Could you merge upstream?

I would suggest to:
- Remove the title ("Welcome to Denkmal.org")
- Add a slight border/shadow to the white font on the image, to ensure readability

wdyt?

**Comment by christopheschwyzer** [comment]
- Agree. 
- I thought we could get a better (more balanced brightness) picture for Graz.

**Comment by christopheschwyzer** [comment]
screen shot 2016-07-17 at 22 24 08
@njam fyi

**Comment by njam** [comment]
I've added 2 small changes, merging…

**Pull request merged**
