### PR TITLE
Add launch banner

### PR DESCRIPTION
**Pull request by christopheschwyzer**
> Feier mit uns den Launch von Denkmal Graz!
14. Oktober 18:00 at Postgarage (Graz), Renée (Basel)

Display X days before launch?

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
screen shot 2016-10-04 at 15 33 03

@njam @NicolasSchmutz wdyt?

**Comment by christopheschwyzer** [comment]
Maybe add a condition to show it only until the launch date…

**Comment by trampy** [comment]
Awesome, looks great!

**Comment by NicolasSchmutz** [comment]
great looks very good!

>Maybe add a condition to show it only until the launch date…

would be good yes!
does is appear every reload?

**Comment by njam** [comment]
Ideas:
- Drop the "2nd" after "Postgarage" because it's not very clear what it means
- Click on X: Hide it, and don't show again
- Click on banner: Navigate to `{linkUrl page='Denkmal_Page_Events' date='2016-10-14'}`

**Comment by christopheschwyzer** [comment]
There is a problem with the linking to a date that's not in range of the week. Seems not so easy to fix. @njam could you help out?
screen shot 2016-10-05 at 19 41 35

**Comment by njam** [comment]
I see, that's https://github.com/denkmal/denkmal.org/pull/461 :(
How about restricting delivery to only the week before, and to stop on the day after? In `Denkmal_Page_Events`: 
```php
$today = $settings->getCurrentDate();
$showBannerGrazLaunch = ($today > new DateTime('2016-10-09') && $today < new DateTime('2016-10-05'));
$viewResponse->set('showBannerGrazLaunch', $showBannerGrazLaunch);
```

On Desktop it takes up quite some space, would be nice if the maximum height was something like 200px? But then we need a second version?

**Comment by christopheschwyzer** [comment]
Hm we could show it like this:
screen shot 2016-10-05 at 20 53 20

But also not so nice.

**Comment by christopheschwyzer** [comment]
Ok found a solution. @njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
