### PR TITLE
Refactor header bar

### PR DESCRIPTION
**Pull request by christopheschwyzer**
closes https://github.com/denkmal/denkmal.org/issues/685

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
@njam please review (php)

**Comment by njam** [comment]
Looks nice!

Notes from testing:
- In the German version the short dates are now "Mo." instead of just "Mo". I think the dot is not needed. (was `substr($weekday, 0, 2)`)
- In the German version the full label looks a bit strange: "Mittwoch 08". The number looks more like a year than a date. Should it be rather "Mittwoch, 8."?
- What's the minimum size we want to support? With 320px and additional play button will not fit. How about a short version? "Mi, 8." instead of "Mittwoch, 8."?

Code:
- date_weekday: Maybe create a separate smarty function for the long version of the weekday menu.

**Comment by christopheschwyzer** [comment]
> date_weekday: Maybe create a separate smarty function for the long version of the weekday menu.

Thought about it as well, but then I'd have to create 2 menus as well - not so nice.

**Comment by christopheschwyzer** [comment]
date-de
Maybe it should just read "Today" for the current day. Hm complicated matter. We should use day of the year. "D124" 🤓

**Comment by njam** [comment]
I would do the short version, so we have space available for the play/pause icon.
Both "So, 12." and "So 12." look good.

**Comment by christopheschwyzer** [comment]
Used without comma, added short version for smaller screens. 
I'm not so happy with smarty function and how the formatting is done, but don't have a better idea. @njam thoughts?

**Pull request merged**
